name: Docker Image CI
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t ecr-${{vars.PROJECT_NAME}} .
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-1
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
      - name: Amazon ECR "Login" Action for GitHub Actions
        id: login-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: ecr-${{vars.PROJECT_NAME}}
        run:
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
